DELETE FROM settings;

INSERT INTO `settings` (`name`, `value`) VALUES
('title', 'Planet PHP FR'),
('atom_link', 'http://planete-php.fr/rss'),
('link', 'http://planete-php.fr'),
('description', 'Tous les blogs PHP francophones'),
('language', 'fr-fr'),
('generator', 'galactus: https://github.com/fmagnan/galactus');

DELETE FROM feeds;

INSERT INTO `feeds` (`name`, `url`, `isEnabled`) VALUES
('Guillaume Bretou (PHPSymfony)', 'http://phpsymfony.com/index.php?feed/rss2', 1),
('Mathieu Robin', 'http://feeds.feedburner.com/Mathieurobincom', 1),
('Kévin Dunglas (Lapin Blanc)', 'http://dunglas.fr/category/programmation/php/feed/', 1),
('Hello Design', 'http://blog.hello-design.fr/index.php?feed/rss2', 1),
('Gilles Février', 'http://gfevrier.kelio.org/blog/feed/', 1),
('Pascal Martin (n+1).zéro', 'http://blog.pascal-martin.fr/feed/rss2', 1),
('Perrick Penet (onpk.net)', 'http://onpk.net/rss', 1),
('Franck Lefevre (Progi1984) - rootslabs', 'http://rootslabs.net/blog/feed', 1),
('Frédéric Hardy (mageekbox.net)', 'http://blog.mageekbox.net/?feed/rss2', 1),
('BlogDevPHP (Frantz Alexis)', 'http://www.blogdevphp.fr/feed/', 1),
('cd ~tigrou/pwet.fr/Blog', 'http://damien.pobel.fr/rss', 1),
('Mère Teresa\'s Blog', 'http://sarahhaim.wordpress.com/feed/', 1),
('Blount (programmation-web.net)', 'http://programmation-web.net/feed/', 1),
('WebRIVER', 'http://webriver.eu/rss.xml', 1),
('Poor Lonesome Coder', 'http://www.plcoder.net/rss.php?rss=Blog', 1),
('Pulsar Informatique', 'http://www.pulsar-informatique.com/actus-blog/latest?format=feed&type=rss', 1),
('Jean-François Lépine', 'http://blog.lepine.pro/atom.xml', 1),
('FoxMask\'z h0m3', 'http://www.foxmask.info/feed/', 1),
('BastNic\'s Blog', 'http://feeds.feedburner.com/bastnic', 1),
('De geek à directeur technique', 'http://www.geek-directeur-technique.com/feed', 1),
('Olivier Noël (alkannoide)', 'http://www.alkannoide.com/feed/', 1),
('Mehdi Kabab (piouPiouM)', 'http://feeds.pioupioum.fr/pioupioum-dev-blog', 1),
('Pierre Li Vigni (symblog.info)', 'http://symblog.info/feed/', 1),
('Anis Berejeb', 'http://www.berejeb.com/feed/', 1),
('Maxence Delannoy (Wiip)', 'http://wiip.fr/rss.xml', 1),
('Christophe Le Bot', 'http://blog.christophelebot.fr/feed/', 1),
('Ulrich (mon-code.net)', 'http://www.mon-code.net/feeds/rssGlobale', 1),
('Mikael Randy', 'http://www.mikaelrandy.fr/atom.xml', 1),
('Yohann Poiron', 'http://feeds2.feedburner.com/design-folio', 1),
('Roms Blog', 'http://www.romainbourdon.com/index.php/feed/', 1),
('Industrialisation PHP', 'http://feeds.feedburner.com/industrialisation-php', 1),
('Stéphane Bourzeix', 'http://www.bourzeix.com/weblog/feed/rss2', 1),
('Nexen.net', 'http://www.nexen.net/component/option,com_rss/Itemid,0/index2.php/feed,RSS2.0/no_html,1/', 1),
('Gerald\'s blog', 'http://www.croes.org/gerald/blog/feed/', 1),
('elePHPant', 'http://www.elephpant.com/rss.xml', 1),
('Jean-Marc Fontaine', 'http://flux.jmfontaine.net/jmfontaine-billets', 1),
('Formation CakePHP', 'http://feeds.feedburner.com/FormationCakephp', 1),
('Aurélien Gérits (Magix cjQuery)', 'http://magix-cjquery.com/feed/rss2', 1),
('Joris Berthelot (rand(0))', 'http://blog.eexit.net/rss/', 1),
('Stéphane Brun (sbnet)', 'http://www.sbnet.fr/feed/', 1),
('Florent Viel (luxifer)', 'https://blog.luxifer.fr/atom.xml', 1),
('Arnaud de Abreu (YrWeb)', 'http://yrweb.fr/feed', 1),
('Nicolas Thouvenin (touv.fr)', 'http://blog.touv.fr/rss.xml', 1),
('Questions des stagiaires', 'http://formatrice.wordpress.com/feed/', 1),
('Webozor', 'http://www.webozor.com/feed', 1),
('PHPSources', 'http://www.phpsources.org/articles-rss.xml', 1),
('j0k3r', 'http://feeds2.feedburner.com/J0k3rn3t', 1),
('Julien Pauli', 'http://blog.developpez.com/julienpauli/feed', 1),
('Etienne Voilliot', 'http://lapetitepausetechnique.net/feed/', 1),
('Brice Favre (peLmeL)', 'http://pelmel.org/dotclear.php/feed/atom', 1),
('Christophe de Saint Léger', 'http://lindev.fr/index.php?feed/rss2', 1),
('Yves Tannier (L\'appartement)', 'http://www.grafactory.net/blog/feed/rss2', 1),
('Fabien Pennequin (blogafab)', 'http://www.blogafab.com/feed/', 1),
('Sutekidane', 'http://feeds2.feedburner.com/sutekidane', 1),
('Loogaroo', 'http://feeds.feedburner.com/Loogaroo', 1),
('Gauthier Delamarre (Free Blog Ware)', 'http://freeblogware.org/?feed=rss2', 1),
('Benjamin Longearet (geekos)', 'http://feeds.feedburner.com/geekos/fr', 1),
('Samuel Martin (creaone)', 'http://blog.creaone.fr/feed/rss2', 1),
('jy[B]log', 'http://ljouanneau.com/blog/feed/atom', 1),
('Blog Technique Elao', 'http://www.elao.com/blog/feed', 1),
('Michael Bertocchi (duPot.org)', 'http://dupot.org/newsrss.rss', 1),
('Thibault Jouannic (miximum.fr)', 'http://www.miximum.fr/feeds/rss.xml', 1),
('Cyruss blog', 'http://www.cyruss.com/index.php?feed/atom', 1),
('Nicolas Hachet', 'http://blog.nicolashachet.com/feed/', 1),
('Alexis Metaireau (notmyidea.org)', 'http://blog.notmyidea.org/feeds/all.atom.xml', 1),
('Matthieu Huguet (BigOrNot?)', 'http://bigornot-fr.blogspot.com/feeds/posts/default?alt=rss', 1),
('Raphael Rougeron', 'http://blog.raphael-rougeron.com/feed/atom', 1),
('Chez Xavier', 'http://lacot.org/syndication.atom', 1),
('AFUP', 'http://www.afup.org/pages/site/rss.php', 1),
('ApéroPHP', 'http://aperophp.net/list.atom', 1),
('Julien Breux', 'http://www.julien-breux.com/feed', 1);

/* semblent morts
 ('Cherry on the ...', 'http://cherryonthe.popnews.com/rss', 1),
 ('Charles Rincheval (DigitalSpirit)', 'http://www.digitalspirit.org/blog/index.php/feed/rss2', 1),
 ('Martin Supiot (webaaz)', 'http://feeds2.feedburner.com/webaaz', 1),
 ('XHTML.net - Loïc', 'http://www.xhtml.net/', 1),
 ('Glagla Dot Org', 'http://www.glagla.org/weblog/', 1),
 ('Kamelot Blog', 'http://le.brol.de.moosh.be/blog/', 1),
 ('Arnaud "Narno" Ligny', 'http://www.narno.com/', 1),
 ('zenProg', 'http://zenprog.com/', 1),
 ('Olivier Hoareau (phppro.fr)', 'http://blog.phppro.fr/', 1),
 ('Hyla Project', 'http://blog.hyla-project.org/', 1),
 ('Pascal Cescato (expert-php)', 'http://www.expert-php.fr/', 1),
 ('Strat&geek', 'http://blog.strategeek.fr', 1),
 ('Alheim', 'http://alheim.fr/', 1),
 ('ZeFredz\'s Blog', 'http://zefredz.frimouvy.org/dotclear/', 1),
 ('Metagoto\'s blog', 'http://blog.runpac.com/', 1),
 ('Coding Style', 'http://www.codingstyle.fr/', 1),
 ('Nicolas Joseph (gege2061)', 'http://gege2061.homecomputing.fr/', 1),
 ('blognote-info.com', 'http://www.blognote-info.com/', 1),
 ('fchfch sur phptothemoon', 'http://phptothemoon.com/fr/blogs/', 1),
 ('Experimental Symfony', 'http://www.experimental-symfony.com/', 1),
 ('Arnaud Limbourg', 'http://www.limbourg.com/arnaud/blog/', 1),
 ('Coolforest', 'http://blog.coolforest.net/', 1),
*/